spring:
  application:
    name: wx-shop--client-consumer
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

server:
  port: 9092

feign:
  sentinel:
    enabled: true


management:
  endpoints:
    web:
      exposure:
        include: "*"
