spring:
  application:
    name: wx-shop-client-provider
  #nacos
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  sentinel:
    transport:
      port: 8720
      dashboard: localhost:8080
  datasource:
    druid:
      url: jdbc:mysql://119.23.105.18:3306/wx-shop?useUnicode=true&characterEncoding=utf-8&useSSL=false
      username: root
      password: 123456
      initial-size: 1
      min-idle: 1
      max-active: 20
      test-on-borrow: true
      driver-class-name: com.mysql.cj.jdbc.Driver


server:
  port: 9998

feign:
  sentinel:
    enabled: true

mybatis:
  type-aliases-package: com.hrh.wx.commons.domain
  mapper-locations: classpath:mapper/*.xml

management:
  endpoints:
    web:
      exposure:
        include: "*"
